name: CMake Worker

on:
  push:
    branches: [ "version-core" ]
  pull_request:
    branches: [ "version-core" ]

jobs:
  release:  
    name: Release
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: fregante/setup-git-user@v2
    
      - name: Install Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Linux Install Libraries
        run: |
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list

          sudo apt-get update
          sudo apt-get install gcc-mingw-w64 g++-mingw-w64 mingw-w64-tools mingw-w64-x86-64-dev
          sudo apt-get install libfreetype6-dev vulkan-sdk libsdl2-dev libglew-dev libopengl-dev libglx-dev libgl1-mesa-dev libglfw3-dev

          wget https://github.com/libsdl-org/SDL/releases/download/release-2.30.2/SDL2-devel-2.30.2-mingw.zip
          unzip ./SDL2-devel-2.30.2-mingw.zip
          sudo cp -r ./SDL2-2.30.2/x86_64-w64-mingw32/* /usr/x86_64-w64-mingw32

          wget https://github.com/vokegpu/.github/releases/download/cross-platform-mingw/x86_64-w64-mingw32.zip
          unzip ./x86_64-w64-mingw32.zip
          yes | sudo cp -r ./x86_64-w64-mingw32/* /usr/x86_64-w64-mingw32/

      - name: Configure Linux-CMake
        run: >
          cmake -B ${{ github.workspace }}/cmake-build-debug
          -S ${{ github.workspace }}
          -G Ninja
          -DCMAKE_CXX_COMPILER=g++
          -DEKG_ENABLE_TEST=0
          -DEKG_LINUX_NOT_FOUND_FREETYPE=1
          -DEKG_FORCE_LINUX=1

      - name: Build Linux-CMake
        run: |
          cmake --build ${{ github.workspace }}/cmake-build-debug
          sudo rm -r -f ${{ github.workspace }}/cmake-build-debug

      - name: Configure Windows-CMake
        run: >
          cmake -B ${{ github.workspace }}/cmake-build-debug
          -S ${{ github.workspace }}
          -G Ninja
          -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++
          -DEKG_ENABLE_TEST=0
          -DEKG_LINUX_NOT_FOUND_FREETYPE=1
          -DEKG_FORCE_WINDOWS=1

      - name: Build Windows-CMake
        run: |
          cmake --build ${{ github.workspace }}/cmake-build-debug

      - name: Read Title
        id: commit_title
        run: echo "message=$(git log --format=%B -n 1 ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Read Description
        id: commit_description
        run: |
          message=$(git log --format=%B -n 1 ${{ github.sha }} | sed -n '2,$p')
          message=$(echo $message | tr '\n' ' ')

          echo "message=$message" >> $GITHUB_OUTPUT

      - name: Release if Needed
        if: startsWith(steps.commit_title.outputs.message, '[release]')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd ${{ github.workspace }}
          python ./devlog/devlog.py -m ${{ steps.commit_title.outputs.message }} -d ${{ steps.commit_description.outputs.message }}
